### ISSUE TITLE
Cannot cast OToMoveParticle to XToMoveParticle

### ISSUE THREAD

**Issue by cbisaillon** [radixdlt/radixdlt#22]
I am trying to run the TicTacToe example in the radix-engine project after pulling from the latest release branch.
I am not able to run the example because of a ClassCastException when running `engine.checkAndStore(atom);` 

Here is the stack trace:
```
Exception in thread "main" java.lang.ClassCastException: class com.radixdlt.examples.tictactoe.TicTacToeConstraintScrypt$OToMoveParticle cannot be cast to class com.radixdlt.examples.tictactoe.TicTacToeConstraintScrypt$XToMoveParticle (com.radixdlt.examples.tictactoe.TicTacToeConstraintScrypt$OToMoveParticle and com.radixdlt.examples.tictactoe.TicTacToeConstraintScrypt$XToMoveParticle are in unnamed module of loader 'app')
	at com.radixdlt.atomos.ParticleDefinition$Builder.lambda$build$2(ParticleDefinition.java:144)
	at com.radixdlt.atomos.ConstraintScryptEnv.lambda$registerParticle$0(ConstraintScryptEnv.java:122)
	at com.radixdlt.atomos.ParticleDefinition$Builder.lambda$build$3(ParticleDefinition.java:145)
	at com.radixdlt.atomos.CMAtomOS.lambda$buildParticleStaticCheck$6(CMAtomOS.java:103)
	at com.radixdlt.constraintmachine.ConstraintMachine.validateMicroInstructions(ConstraintMachine.java:355)
	at com.radixdlt.constraintmachine.ConstraintMachine.validate(ConstraintMachine.java:431)
	at com.radixdlt.engine.RadixEngine.staticCheck(RadixEngine.java:171)
	at com.radixdlt.engine.RadixEngine.checkAndStore(RadixEngine.java:270)
	at com.radixdlt.engine.RadixEngine.checkAndStore(RadixEngine.java:258)
	at com.radixdlt.examples.tictactoe.TicTacToeRunner.main(TicTacToeRunner.java:262)
```

Java Version: openjdk 11.0.9.1 2020-11-04
Gradle Version: 6.7.1

**Comment by talekhinezh** [comment]
@cbisaillon Thanks for catching! I have a PR ready to get merged which should fix this: https://github.com/radixdlt/radixdlt/pull/24
