### ISSUE TITLE
No suitable address found

### ISSUE THREAD

**Issue by iamyulong** [radixdlt/radixdlt#269]
Hi Team,

I failed to run the latest release `radixdlt-1.0-beta.32` with betanet:
```
# 2021-05-10T22:45:11,986 [INFO/RuntimePropertiesHostIp/main] (RuntimePropertiesHostIp.java:62) - No suitable address found
# 2021-05-10T22:45:11,986 [INFO/EnvironmentHostIp/main] (EnvironmentHostIp.java:65) - No suitable address found
# 2021-05-10T22:45:12,062 [INFO/NetworkQueryHostIp/main] (NetworkQueryHostIp.java:124) - No suitable address found
# 2021-05-10T22:45:12,065 [FATAL/Radix/main] (Radix.java:126) - Unable to start
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException: Could not determine host IP address
  at com.radixdlt.network.transport.udp.UDPTransportModule.natHandlerProvider(UDPTransportModule.java:43) (via modules: com.radixdlt.RadixNodeModule -> com.radixdlt.network.transport.udp.UDPTransportModule)
  while locating com.radixdlt.network.transport.udp.NatHandler
    for the 6th parameter of com.radixdlt.network.transport.udp.NettyUDPTransportImpl.<init>(NettyUDPTransportImpl.java:102)
  while locating com.radixdlt.network.transport.udp.NettyUDPTransportImpl
  while locating com.radixdlt.network.transport.Transport annotated with @com.google.inject.internal.Element(setName=,uniqueId=103, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.radixdlt.network.transport.Transport>
    for the 1st parameter of com.radixdlt.network.transport.FirstMatchTransportManager.<init>(FirstMatchTransportManager.java:49)
  while locating com.radixdlt.network.transport.FirstMatchTransportManager
  while locating com.radixdlt.network.messaging.TransportManager
    for the 3rd parameter of com.radixdlt.network.messaging.MessageCentralImpl.<init>(MessageCentralImpl.java:90)
  while locating com.radixdlt.network.messaging.MessageCentralImpl
  at com.radixdlt.network.messaging.MessageCentralModule.configure(MessageCentralModule.java:50) (via modules: com.radixdlt.RadixNodeModule -> com.radixdlt.network.messaging.MessageCentralModule)
  while locating com.radixdlt.network.messaging.MessageCentral
    for the 3rd parameter of com.radixdlt.network.addressbook.PeerManager.<init>(PeerManager.java:145)
  while locating com.radixdlt.network.addressbook.PeerManager

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097) ~[guice-4.2.3.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[guice-4.2.3.jar:?]
	at org.radix.Radix.start(Radix.java:146) ~[radixdlt-1.0-beta.32.jar:?]
	at org.radix.Radix.main(Radix.java:124) ~[radixdlt-1.0-beta.32.jar:?]
Caused by: java.lang.IllegalStateException: Could not determine host IP address
	at com.radixdlt.network.transport.udp.UDPTransportModule.lambda$natHandlerProvider$2(UDPTransportModule.java:75) ~[radixdlt-1.0-beta.32.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
```

It seems the kernel is unable to detect my IP address. I'm behind a home router. Any workaround?

Thanks,
Yulong

**Comment by iamyulong** [comment]
For anyone who is experiencing the same problem. Please follow the official installation guide, https://docs.radixdlt.com/
